FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    wget \
    gcc \
    g++ \
    make \
    git \
    ca-certificates \
    sqlite3 \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

# Установка Go
ENV GO_VERSION=1.21.5
RUN wget -q https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
    rm go${GO_VERSION}.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV CGO_ENABLED=1

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Устанавливаем testify
RUN go get github.com/stretchr/testify

CMD ["go", "test", "./...", "-v"]