  {{- if .Values.postgresql.enabled }}
BIND_API_DB_HOST: {{ printf "%s-postgresql" .Release.Name | quote }}
BIND_API_DB_PORT: "5432"
BIND_API_DB_USER: {{ .Values.postgresql.auth.username | quote }}
BIND_API_DB_NAME: {{ .Values.postgresql.auth.database | quote }}
BIND_API_DB_SSLMODE: "disable"
  {{- else if .Values.externalPostgresql.enabled }}
# Внешний PostgreSQL
BIND_API_DB_HOST: {{ .Values.externalPostgresql.host | quote }}
BIND_API_DB_PORT: {{ .Values.externalPostgresql.port | default "5432" | quote }}
BIND_API_DB_USER: {{ .Values.externalPostgresql.user | quote }}
BIND_API_DB_NAME: {{ .Values.externalPostgresql.database | quote }}
BIND_API_DB_SSLMODE: {{ .Values.externalPostgresql.sslMode | default "disable" | quote }}
  {{- end }}

  {{- if .Values.externalPostgresql.schema }}
BIND_API_DB_SCHEMA: {{ .Values.externalPostgresql.schema | quote }}
  {{- end }}