{{- if and .Values.zonesStorage.enabled (eq .Values.role "master") .Values.zonesStorage.createPV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "bind-api.fullname" . }}-zones-pv
  labels:
    {{- include "bind-api.labels" . | nindent 4 }}
    type: local
spec:
  capacity:
    storage: {{ .Values.zonesStorage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.zonesStorage.storageClass }}
  hostPath:
    path: {{ .Values.zonesStorage.hostPath | default "/var/openebs/bind-zones" }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
{{- end }}
{{- /* Убрать пустой документ между условиями */ -}}
{{- if and .Values.postgresql.enabled (eq .Values.role "master") .Values.postgresql.primary.persistence.createPV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "bind-api.fullname" . }}-postgresql-pv
  labels:
    {{- include "bind-api.labels" . | nindent 4 }}
    type: local
spec:
  capacity:
    storage: {{ .Values.postgresql.primary.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.postgresql.primary.persistence.storageClass }}
  hostPath:
    path: {{ .Values.postgresql.primary.persistence.hostPath | default "/var/openebs/bind-postgresql" }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
{{- end }}