{{- if eq .Values.role "replica" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bind-api.fullname" . }}-replica
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bind-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
spec:
  clusterIP: None
  selector:
    {{- include "bind-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: replica
  ports:
    - port: {{ include "bind-api.apiPort" . }}
      targetPort: api
      name: api
    - port: 53
      targetPort: dns-tcp
      name: dns-tcp
      protocol: TCP
    - port: 53
      targetPort: dns-udp
      name: dns-udp
      protocol: UDP
{{- end }}